[profile.default]
src = "src"
out = "out"
evm_version = "cancun"
libs = ["lib"]
remappings = [
    "@solmate/=lib/solmate/src/",
    "@std/=lib/forge-std/src/",
    "@clones/=lib/clones-with-immutable-args/src/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
    "solidity-stringutils/=lib/openzeppelin-foundry-upgrades/lib/solidity-stringutils/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
amoy = "https://rpc.ankr.com/polygon_amoy"

[profile.anvil]
block_time = 12
fork_rpc_url = "https://rpc.ankr.com/polygon_amoy"


